### PR TITLE
fix/touchup auth experience

### LINKED ISSUE #139: Bug: initial sign in and redirect doesn't display the right content
## Why

See the attached video for explanation (a similar thing happens for admins as well)

(tl;dw: logging in initially displays placeholder content instead of the actual page content)

## What to do
- Make it so logging in displays the expected page content directly instead of requiring a refresh
  - I suspect this might have to do with the `useAuth` hook in `src/hooks/useAuth.ts`, possibly due to the query for user data not actually updating the `user` variable in `src/components/AuthedApp.tsx`, but this is just a hunch

https://github.com/user-attachments/assets/f5bf26da-5211-492f-8b7a-7dddc0ff39ac

### PR DESCRIPTION
**Pull request by huang0h**
### ℹ️ Issue

Closes #139 

### 📝 Description

Briefly list the changes made to the code:

- Added support for this.
- And removed redunant use of that.
- Also this was included for reasons.

### ✔️ Verification

What steps did you take to verify your changes work? These should be clear enough for someone to be able to clone the branch and follow the steps themselves. 

Provide screenshots of any new components, styling changes, or pages. 

### 🏕️ (Optional) Future Work / Notes

Did you notice anything ugly during the course of this ticket? Any bugs, design challenges, or unexpected behavior? Write it down so we can clean it up in a future ticket!

### CODE REVIEW

File: src/hooks/useAuth.ts [hunk 1]
```diff
@@ -15,7 +18,22 @@ export default function useAuth(): [boolean, boolean, User | undefined] {
...
+        setAuthState(AuthState.SignedIn);
+        setUser(currentUser);
+      } catch (e) {
+        setAuthState(AuthState.SignedOut);
+        setUser(null);
+      }
+    }
+
+    checkCurrentUser();
+  }, []);
```
Comment (huang0h) [inline src/hooks/useAuth.ts:34]: note: this is probably not the best way of doing things (ideally auth info should probably be in a global context, which this hook just accesses for you). but, in the interest of not spending a ton of time refactoring this and not potentially breaking things, i'm just adding a check for if the user is already signed in and setting the state that way
